### ISSUE TITLE
build failure due to push auth

### ISSUE THREAD

**Issue by cuericlee** [AliyunContainerService/alicloud-controller-manager#1]
#### When I build controller, I saw push error, I suppose we don’t expect to push this image to common registry. So I guess you might need to remove push action from Makefile avoid build failure.

.PHONY: clean binary build push -> .PHONY: clean binary

```
docker push registry.cn-hangzhou.aliyuncs.com/google-containers/alicloud-controller-manager:v0.1.0
The push refers to a repository [registry.cn-hangzhou.aliyuncs.com/google-containers/alicloud-controller-manager]
be8d9330aabf: Preparing
94f61b47f81f: Preparing
7f7a065d245a: Preparing
f96e6b25195f: Preparing
c56153825175: Preparing
ae620432889d: Waiting
a2022691bf95: Waiting
unauthorized: authentication required
Makefile:16: recipe for target 'push' failed
```

**Comment by spacexnice** [comment]
@Crazykev   pls take a look.  thanks.

**Comment by Crazykev** [comment]
@cuericlee Thanks for the advise. We will add a `release` tag for this build and push when release our 0.10 version and remove the default behavior of build and push. 
You can use `make binary` instead if only want to build a alicloud-controller-manager binary. And you can also `export REGISTRY=<YOUR_REGISTRY_NAME>` and `make` to build and push to your own docker registry.
