### ISSUE TITLE
Aliyun API InvalidParameter error

### ISSUE THREAD

**Issue by jia-jerry** [AliyunContainerService/alicloud-controller-manager#11]
When I tried to expose a test Nginx svc with a loadbalancer, an error occures in the controller manager.

E0814 00:16:35.074058   11287 service_controller.go:1123] Failed to process service default/nginx. Retrying in 10s: failed to ensure load balancer for service default/nginx: Aliyun API Error: RequestId: 2FB40702-3271-4C27-8564-2B9E9BFF2F3D Status Code: 400 Code: InvalidParameter Message: The specified HealthCheckType is invalid.

**Comment by denverdino** [comment]
what is your configuration? Thanks

**Comment by aoxn** [comment]
Fix in https://github.com/AliyunContainerService/alicloud-controller-manager/pull/12/files .

**Comment by jia-jerry** [comment]
No special configuration. 
#12  fixed the issue. Just confirmed.
