### ISSUE TITLE
Why should we use Daemonset to deploy alicloud controller manager

### ISSUE THREAD

**Issue by jia-jerry** [AliyunContainerService/alicloud-controller-manager#13]
In the example [getting-started](
https://github.com/AliyunContainerService/alicloud-controller-manager/blob/cloudprovider-v1.9.3-e/docs/getting-started.md), the CCM is deployed in a DaemonSet. 
I tried to deploy it as a Deployment and found it also worked.

Question: Is there any special purpose to deploy it in a DaemonSet?

**Comment by aoxn** [comment]
It is easy to have only one replica on each node for daemonset.

**Comment by aoxn** [comment]
It should work for deployment too. Your choice.

**Comment by jia-jerry** [comment]
What is the case that we deploy one replica on each node?
