### ISSUE TITLE
[CIP] Enable the cloud controller to accept a customized Tags to create a server load balancer

### ISSUE THREAD

**Issue by jia-jerry** [AliyunContainerService/alicloud-controller-manager#14]
There are some cases that some VMs are destroyed, on which K8S cluster was running.  However, server load balancers created by Alicloud CCM could not be released because of lack of necessary labels. 

Solution:
Enable -tags arguments when starting CCM.
For example:
./alicloud-controller-manager --tags=cluster=a --tags=role=b
As a result, all loadbalancers createdy by the CCM will have tags like cluster=a/role=b.

**Comment by aoxn** [comment]
CCM now tagged the newly created LB with kubernetes.do.not.delete.  You can identify your ccm created LB by this tag. Thanks.

**Comment by aoxn** [comment]
@jia-jerry

**Comment by jerryjxj** [comment]
But this can't discriminate LBs created by different K8S clusters. If I try to destroy one K8S cluster, I can't tell all LBs created by **THIS** k8s cluster.

**Comment by jia-jerry** [comment]
But this can't discriminate LBs created by different K8S clusters. If I try to destroy one K8S cluster, I can't tell all LBs created by THIS k8s cluster.

**Comment by aoxn** [comment]
1. Delete all the service before the cluster is deleted.
2. Rename your LoadBalancer to something meaningful.  (upgrade your ccm first) . see https://yq.aliyun.com/articles/608563?spm=a2c4e.11153940.blogrightarea608575.12.57ed1279kTVKfq
