### ISSUE TITLE
现在支持 Cloud Controller Mananger (CCM) 吗? 

### ISSUE THREAD

**Issue by triumph** [AliyunContainerService/alicloud-controller-manager#15]
现阶段是对Cloud Provider 的支持,  还是已经可以支持   Cloud Controller Mananger (CCM) 了,  kebeadm 如何 安装配置 alicloud-controller-manager  (在1.11.x 版本中)

**Comment by triumph** [comment]
I0829 09:56:39.540204       1 node_controller.go:85] Sending events to api server.
E0829 09:56:39.549681       1 node_controller.go:133] Error monitoring node status: nodes is forbidden: User "system:serviceaccount:kube-system:cloud-node-controller" cannot list nodes at the cluster scope
E0829 09:56:39.550130       1 node_controller.go:212] Error monitoring node status: nodes is forbidden: User "system:serviceaccount:kube-system:cloud-node-controller" cannot list nodes at the cluster scope
I0829 09:56:39.563016       1 client_builder.go:233] Verified credential for pvl-controller/kube-system
I0829 09:56:39.563569       1 pvlcontroller.go:106] Starting PersistentVolumeLabelController



E0829 09:56:39.592582       1 reflector.go:205] k8s.io/cloud-provider-alibaba-cloud/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:kube-system:shared-informers" cannot list nodes at the cluster scope
E0829 09:56:39.592628       1 reflector.go:205] k8s.io/cloud-provider-alibaba-cloud/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:kube-system:shared-informers" cannot list services at the cluster scope
E0829 09:56:39.592779       1 reflector.go:205] k8s.io/cloud-provider-alibaba-cloud/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:kube-system:shared-informers" cannot list endpoints at the cluster scope
I0829 09:56:40.564686       1 reflector.go:240] Listing and watching *v1.PersistentVolume from k8s.io/cloud-provider-alibaba-cloud/vendor/k8s.io/kubernetes/pkg/controller/cloud/pvlcontroller.go:109
E0829 09:56:40.568881       1 reflector.go:205] k8s.io/cloud-provider-alibaba-cloud/vendor/k8s.io/kubernetes/pkg/controller/cloud/pvlcontroller.go:109: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:serviceaccount:kube-system:pvl-controller" cannot list persistentvolumes at the cluster scope
I0829 09:56:40.592716       1 reflector.go:240] Listing and watching *v1.Node from k8s.io/cloud-provider-alibaba-cloud/vendor/k8s.io/client-go/informers/factory.go:86
E0829 09:56:40.593428       1 reflector.go:205] k8s.io/cloud-provider-alibaba-cloud/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:kube-system:shared-informers" cannot list nodes at the cluster scope
I0829 09:56:40.593725       1 reflector.go:240] Listing and watching *v1.Service from k8s.io/cloud-provider-alibaba-cloud/vendor/k8s.io/client-go/informers/factory.go:86
E0829 09:56:40.594314       1 reflector.go:205] k8s.io/cloud-provider-alibaba-cloud/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:kube-system:shared-informers" cannot list services at the cluster scope

**Comment by triumph** [comment]
RBAC  账户设置如下
https://raw.githubusercontent.com/triumph/myk8s/master/alicloud-ELB/01.yml

**Comment by aoxn** [comment]
RBAC的设置参考kube-controller-manager, 稍后我会补充一个文档。

**Comment by aoxn** [comment]
Kubeadm 设置cloudprovider=external， 然后自行apply ccm组件

**Comment by triumph** [comment]
现有几个疑问
1.现在支持的k8s版本是v.1.10.x 是嘛?   
2.kube-apiserver  kube-controller-manage   kubelet  启动都需要设置 cloudprovider=external 是吧.
3.kube-apiserver服务还需要其他设置嘛?比如    --disable-admission-plugins=PersistentVolumeLabel                          --enable-admission-plugins=Initializers,xxx,xxx    --runtime-config=admissionregistration.k8s.io/v1alpha1
4.  如下yml 还要运行嘛?
kind: InitializerConfiguration
apiVersion: admissionregistration.k8s.io/v1alpha1
metadata:
  name: pvlabel.kubernetes.io
initializers:
  - name: pvlabel.kubernetes.io
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - "*"
      resources:
      - persistentvolumes


我是参考下面的资料的,所以有些疑问
https://v1-10.docs.kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/

**Comment by aoxn** [comment]
1. 目前支持v1.10.4版本。
2. 都需要
3 & 4 . 参考文档https://github.com/AliyunContainerService/alicloud-controller-manager/tree/master/docs

**Comment by triumph** [comment]
我看你 docs/examples/kubelet.service 文件有  --enable-controller-attach-detach=false  的配置 ,那和你们的 osi-plugin 要求的 --enable-controller-attach-detach=true   想冲突了.   参考页面如下      https://github.com/AliyunContainerService/csi-plugin?spm=a2c4e.11153940.blogcont623259.18.316f56e9whoawC

**Comment by aoxn** [comment]
kubectl get no -o yaml |grep provider      
What is the output?

**Comment by aoxn** [comment]
kubectl get no -o yaml |grep name:

**Comment by triumph** [comment]
# kubectl get no -o yaml |grep provider
    providerID: cn-hangzhou.bp1148jq0xmy5djio147
    providerID: cn-hangzhou.i-bp1148jq0xmy5djio148

**Comment by triumph** [comment]
我修改下 在尝试下

**Comment by triumph** [comment]
修改下就好了   谢谢

**Comment by vsxen** [comment]
CloudNetwork: Only Alibaba Cloud VPC network is supported.
如果我只使用slb的话 可以用在经典网络吗（业务遗留）？
还有cluster autoscaling 是否还在维护？

**Comment by denverdino** [comment]
@vsxen 
不支持经典网络
Auto Scaler 最新介绍 https://yq.aliyun.com/articles/636831
