### ISSUE TITLE
Node name restriction

### ISSUE THREAD

**Issue by jia-jerry** [AliyunContainerService/alicloud-controller-manager#19]
To make the controller works, we need to specify --hostname-override [region].[instanceid]. This is not required in other CCM like AWS or GCP. Why should we put this constraint?

I noticed the node Name usage in some code like line 198 in alicloud.go:
```golang
i, err := c.climgr.Instances().findInstanceByNode(types.NodeName(v.Name))
```
Is it possible to just find by  v.Spec.ProviderID instead of v.Name ?

**Comment by jia-jerry** [comment]
@aoxn  If it is OK to get instance just only from ProviderID, I will provide a PR. Thanks.

**Comment by aoxn** [comment]
prefer to https://github.com/kubernetes/cloud-provider-alibaba-cloud/issues/8
