### ISSUE TITLE
设置了--hostname_override and --provider-id 之后无法注册节点

### ISSUE THREAD

**Issue by SILLKY** [AliyunContainerService/alicloud-controller-manager#6]
Unable to register node "i-bp1fuxiq5o346xa5esfo" with API server: nodes "i-bp1fuxiq5o346xa5esfo" is forbidden: node "izbp1fuxiq5o346xa5esfoz" cannot modify node "i-bp1fuxiq5o346xa5esfo

**Comment by SILLKY** [comment]
https://kubernetes.io/docs/admin/admission-controllers/#noderestriction

you should close NodeRestriction  in admission-control of api-server

**Comment by aoxn** [comment]
close NodeRestriction would cause some security risk.  A proper way is to config correct authorization for your kubelet node.   kubeadm will do it for you If you are not familiar with authorization.
