### ISSUE TITLE
确认一下以后是否还有继续维护

### ISSUE THREAD

**Issue by XdaTk** [AliyunContainerService/alicloud-controller-manager#7]
想确认一下，阿里云以后还会继续维护Kubernetes的Cloud Manager 和 FlexVolume，如果不再继续维护，请及时通知一下。对于阿里云在售的Kubernetes的方案，拥有许多定制化的问题，所以我们更加希望能自己搭建Kubernetes集群

**Comment by aoxn** [comment]
在维护，后面会有更新。

**Comment by denverdino** [comment]
方便的时候加一下钉钉，我们也可以了解您定制化的需求，看如何更好支持。

**Comment by decker502** [comment]
我们有同样的需求,请问怎么加钉钉?
